name=TinyU2F
version=1.0.0
author=VerbalJungle
maintainer=VerbalJungle <VerbalJungle@proton.me>
sentence=Lightweight library to use your SoC as a U2F authenticator 
paragraph=TinyU2F is a lightweight, device-agnostic U2F/FIDO hardware authenticator Arduino IDE library. It transforms any Adafruit TinyUSB-compatible microcontroller into a U2F passkey.
category=Communication
url=https://github.com/VerbalJungle/TinyU2F
architectures=*
depends=microecc, Crypto
includes=TinyU2F.h
dot_a_linkage=false
